/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import apidbms2.*;
        

/**
 *
 * @author Jonatan
 */
public class Interfaz extends javax.swing.JFrame {
     
    boolean esAdmi; //variable control usuario
    String nombreBD;
    ApiDBMS2 conexion;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        esAdmi=false;
        nombreBD="";
        
        this.jButton2.setVisible(false);
        this.jButton5.setVisible(false);
        this.jMenuBar1.setVisible(false);
        this.jTextArea1.setVisible(false);
        this.jTextArea2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Background2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Background3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Background = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(901, 650));
        setMinimumSize(new java.awt.Dimension(901, 650));
        setPreferredSize(new java.awt.Dimension(901, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 51));
        jLabel1.setText("Connect to Database");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 90, 181, 27);

        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setText("Hostname");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(269, 127, 70, 23);

        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("Port");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(269, 156, 130, 24);

        jButton1.setText("Conectar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 210, 100, 23);
        jButton1.getAccessibleContext().setAccessibleDescription("");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(357, 128, 205, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(357, 158, 205, 20);

        jButton5.setText("Ejecutar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(400, 270, 100, 23);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 102));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 270, 140, 23);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 210, 110, 23);

        Background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/1916561.jpg"))); // NOI18N
        getContentPane().add(Background2);
        Background2.setBounds(0, 0, 900, 640);

        jTextArea2.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setMaximumSize(new java.awt.Dimension(164, 94));
        jTextArea2.setMinimumSize(new java.awt.Dimension(164, 94));
        jTextArea2.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 300, 880, 270);

        Background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/1916561.jpg"))); // NOI18N
        getContentPane().add(Background3);
        Background3.setBounds(4, 0, 900, 640);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 880, 230);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/1916561.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 900, 640);

        jMenu1.setText("Ver");

        jMenuItem1.setText("Esquema actual");
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Bases de datos");
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Archivo de Registro");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem4.setText("Cerrar sesion");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String host=this.jTextField1.getText();
        String port= this.jTextField2.getText();
        boolean conexion= this.Conectar(host, port);
        if (!conexion){ //si no hay conexion
            this.jLabel4.setText("No conectado");
        }
        else{ // si hay conexion
            this.PantallaSolUsu();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String usuario=this.jTextField1.getText();
        String contrasena= this.jTextField2.getText();
        boolean checkUsuario= this.existeUsuario(usuario, contrasena);
        
        if (!checkUsuario){ //si no existe el usuario
            this.jLabel4.setText("Datos inválidos");
        }
        else{ //si los datos son validos
            this.PantallaInicio();
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String text= this.jTextArea1.getText();
        String []QueryArray= this.QueryToArray(text);
        String Query= "";
        for (int i=0; i<QueryArray.length;i++){
            Query=Query+"/"+QueryArray[i];
        }
        Query= Query+"/";
        String TipoConsulta= conexion.SendReceive("T,"+Query);
        if (TipoConsulta.length()>3){
            this.jTextArea2.setText("Error, no puede haber mas de un tipo de comando en la consulta!");
        }
        else if (TipoConsulta.length()<3){
            this.jTextArea2.setText("Error, no se encontro ningun comando valido!");
        }
        else if (TipoConsulta.equals("CLP") && !esAdmi){
            this.jTextArea2.setText("Usted no posee permisos para ejecutar comandos CLP!");
        }
        else{
            String respuesta= conexion.SendReceive(Query);
            this.jTextArea2.setText(respuesta);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

//////////////////////////////////////////////Funciones auxiliares///////////////////////////////// 
    
    private boolean Conectar(String host, String port){ //funcion que usa el api para conectarse a la bd
        int p=0;
        try{
            p= Integer.parseInt(port);
        }
        catch (Exception e){
            return false;
        }
        conexion= new ApiDBMS2(host, p);
        String respuesta= conexion.SendReceive("Prueba");
        if (!respuesta.equals("Connected")){
            System.out.println(respuesta);
            return false;
        }
        else{
            return true;
        }
    }
    
    private boolean existeUsuario(String usuario, String contrasena){ //funcion que verifica la exst. de usuario y si es admi.
        String respuesta= conexion.SendReceive("C,"+usuario+","+contrasena);
        if (respuesta.equals("Administrador")){
            esAdmi=true;
            return true;
        }
        else if (respuesta.equals("Usuario")){
            esAdmi=false;
            return true;
        }
        else{
            return false;
        }
    }
    
    private boolean existeBase(String nombreBd){
        this.nombreBD=nombreBd;
        return true;
    }
    
    private void PantallaSolUsu(){ //pantalla solicitar usuario
        this.jButton1.setVisible(false);
        this.jMenuBar1.setVisible(false);
        this.jTextArea1.setVisible(false);
        this.jTextArea2.setVisible(false);
        this.jButton5.setVisible(false);
        this.jButton2.setVisible(true);
        this.Background2.setVisible(true);
        this.jLabel1.setVisible(true);
        this.jLabel1.setText("Autenticacion");
        this.jTextField1.setVisible(true);
        this.jTextField2.setVisible(true);
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jLabel2.setVisible(true);
        this.jLabel3.setVisible(true);
        this.jLabel4.setVisible(true);
        this.jLabel2.setText("Usuario");
        this.jLabel3.setText("Contraseña");
        this.jLabel4.setText("Conectado!");
        this.jLabel4.setLocation(402, 271);
    }
    
    private void PantallaInicio(){ //pantalla inicio (con base especifica y todo)
        this.jTextField1.setVisible(false);
        this.jTextField2.setVisible(false);
        this.jButton1.setVisible(false);
        this.jButton2.setVisible(false);
        this.jLabel2.setVisible(false);
        this.jLabel3.setVisible(false);
        this.Background2.setVisible(false);
        this.Background3.setVisible(false);
        
        this.jLabel1.setVisible(true);
        this.jMenuBar1.setVisible(true);
        this.jTextArea1.setVisible(true);
        this.jTextArea2.setVisible(true);
        this.jButton5.setVisible(true);
        this.jTextArea2.setEditable(false);
        
        this.jLabel1.setText("Query command line");
        this.jLabel1.setLocation(10, 0);
        
        String text= "Conectado ";
        if (this.esAdmi){
            text= text+"(Admin)";
        }
        else{
            text= text+"(Usu)";
        }

        this.jLabel4.setText(text);
        this.jLabel4.setLocation(10, 570);
    }
    
    private String[] QueryToArray(String Query){ // toma la entrada del area de texto y genera arreglo
        String linea="";
        int indice=0;
        for (int i=0; i<Query.length();i++){
            if (Query.charAt(i)=='\n'){
                indice=indice+ this.QueryToArrayAux(linea).length;
                linea="";
            }
            else{
                linea= linea+Query.charAt(i);
                if (i+1==Query.length() && linea.length()!=0){
                    indice=indice+ this.QueryToArrayAux(linea).length;
                    linea="";
                }
            }
        }
        String out[]= new String[indice];
        indice=0;
        for (int i=0; i<Query.length();i++){
            if (Query.charAt(i)=='\n'){
                String [] aux= this.QueryToArrayAux(linea);
                for (int j=0; j<aux.length; j++){
                    out[indice]= aux[j];
                    indice++;
                }
                linea="";
            }
            else{
                linea= linea+Query.charAt(i);
                if (i+1==Query.length() && linea.length()!=0){
                    String [] aux= this.QueryToArrayAux(linea);
                    for (int j=0; j<aux.length; j++){
                          out[indice]= aux[j];
                          indice++;
                    }
                    linea="";
                }
            }
        }
        return out;
    }
    
    private String[] QueryToArrayAux(String linea){
        int indice=0;
        String palabra="";
        for (int i=0; i<linea.length(); i++){
            if (linea.charAt(i)==' '){
                indice++;
                palabra="";
            }
            else{
                palabra= palabra+linea.charAt(i);
                if (i+1==linea.length() && palabra.length()!=0){
                    indice++;
                    palabra="";
                }
            }
        }
        String out[]= new String [indice];
        indice=0;
        palabra="";
        for (int i=0; i<linea.length(); i++){
            if (linea.charAt(i)==' '){
                out[indice]=palabra;
                indice++;
                palabra="";
            }
            else{
                palabra= palabra+linea.charAt(i);
                if (i+1==linea.length() && palabra.length()!=0){
                    out[indice]=palabra;
                    indice++;
                    palabra="";
                }
            }
        }
        return out;
    }
    
    public void ImprimirArregloEnAreaTexto(String [] arreglo){
        String imprimir="";
        for (int i=0; i<arreglo.length;i++){
            imprimir= imprimir+arreglo[i]+" ";
        }
        this.jTextArea2.setText(imprimir);
    }
    ////////////////////////////////////////fin////////////////////////////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Background2;
    private javax.swing.JLabel Background3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
